### ISSUE TITLE
Latest Firmware Support

### ISSUE THREAD

**Issue by actraiser30** [KMFDManic/RetroAami-Xtreme#1]
Hello is it possible to update RetroAami-Xtreme so it works with the latest A500 Mini firmware v1.1.1 ??

i mean i saw the method to switch between firmwares and its not an option for me as its high risk and im not so experienced with that stuff.

the Pandory Mod that its based on Retroarch 1.10.3 works great with the latest firmware but it lacks of cores and optimizations

https://github.com/TeamPandory/pandory500

could it be possible to ask for info from the Pandory Mod developer on how to make RetroAami-Xtreme to work with latest Firmware???

ps: i cannot seem to find the extra cores archive:  KMFDManic-Xtreme-Cores.7z 

Thank you

**Comment by KMFDManic** [comment]
I have already tried to contact the developer of Pandory Mod, and was completely ignored.  So, myself and the other involved in RetroAami went a different route.  It was also discovered that there was obfuscation

**obfuscation removal commit**
https://github.com/KMFDManic/RetroAami-Xtreme/commit/dc4eda00936ae9ffff320c3fcde0e6d38aac8f5d

which violated open source licenses, wherein, if one attempted to alter certain Pandory perimeters, you would inevitably crash your system.  With that being said, I have zero interest in working with Pandory, due to this deception.  I would suggest either sticking with Pandory, as is, or going the "multi-firmware" route, and taking the plunge, if you truly want to be able to use RetroAami Xtreme.  I know this isn't the answer you wanted.  But, within the last many years in the emulation scene, there really is no room for deception and drama, especially when Open Source is something that is meant for all to enjoy.
